# Generated by Django 5.2.15 on 2026-06-10 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('org', '0002_company_address_company_currency_company_sms_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('waiting', 'Waiting'), ('set', 'Set'), ('attended', 'Attended'), ('paid', 'Paid')], default='incoming', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Present'), (0, 'Absent'), (2, 'Late')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='org.company')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='crm.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='crm.student')),
            ],
        ),
    ]
