# Generated by Django 5.2.15 on 2026-09-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_group_room_end_date_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='days',
            field=models.IntegerField(choices=[(1, 'Odd days'), (2, 'Even days'), (3, 'Weekend days'), (4, 'Every day'), (5, 'Other')], default=1),
        ),
    ]
