# Generated by Django 5.2.15 on 2026-09-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_student_photo_student_school_alter_group_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_telegram',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='telegram',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
