# Generated by Django 5.2.15 on 2026-09-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_lead_address_lead_comment_lead_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_students', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
