# Generated by Django 5.2.15 on 2026-09-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_student_address_student_comment_student_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('trial_booked', 'Записан на пробный'), ('attended', 'Был на уроке (Думает)'), ('rejected', 'Отказ / Архив'), ('incoming', 'Incoming'), ('waiting', 'Waiting'), ('set', 'Set'), ('paid', 'Paid')], default='trial_booked', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(1, 'Пробный (Trial)'), (2, 'Заморозка (Frozen)'), (5, 'Активный (Active)'), (6, 'Должник (Debtor)'), (7, 'Ушел после пробного'), (8, 'Отчислен / Ушел'), (9, 'Завершил / Выпускник')], default=1),
        ),
    ]
