# Generated by Django 5.2.15 on 2026-09-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_lead_stage_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='trial_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='trial_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
