# Generated by Django 5.2.15 on 2026-09-12 14:49

from django.db import migrations, models


def copy_full_name_to_first_last(apps, schema_editor):
    Lead = apps.get_model('crm', 'Lead')
    for lead in Lead.objects.all():
        raw_name = (getattr(lead, 'full_name', '') or '').strip()
        if raw_name:
            parts = raw_name.split(None, 1)
            lead.first_name = parts[0]
            lead.last_name = parts[1] if len(parts) > 1 else ''
            lead.save(update_fields=['first_name', 'last_name'])


def copy_first_last_to_full_name(apps, schema_editor):
    Lead = apps.get_model('crm', 'Lead')
    for lead in Lead.objects.all():
        lead.full_name = f'{lead.first_name} {lead.last_name}'.strip()
        lead.save(update_fields=['full_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_lead_trial_date_student_trial_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.RunPython(copy_full_name_to_first_last, copy_first_last_to_full_name),
        migrations.RemoveField(
            model_name='lead',
            name='full_name',
        ),
    ]
