# Generated by Django 5.2.15 on 2026-09-12 15:05

from django.db import migrations, models


def remap_old_statuses(apps, schema_editor):
    Student = apps.get_model('crm', 'Student')
    # 5 (ACTIVE) and 6 (DEBTOR) -> 1 (STUDYING)
    Student.objects.filter(status__in=[5, 6]).update(status=1)
    # 7 (LEFT_TRIAL) -> 8 (LEFT)
    Student.objects.filter(status=7).update(status=8)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_lead_full_name_lead_first_name_lead_last_name'),
    ]

    operations = [
        migrations.RunPython(remap_old_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(1, 'Обучается'), (2, 'Заморозка (Frozen)'), (8, 'Отчислен / Ушел'), (9, 'Завершил курс (Graduated)')], default=1),
        ),
    ]
