# Generated by Django 5.2.15 on 2026-09-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_offset',
            field=models.IntegerField(default=0),
        ),
    ]
