# Generated by Django 5.2.15 on 2026-09-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_student_payment_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
