# Generated by Django 5.2.15 on 2026-09-16 14:02

from django.db import migrations, models


def backfill_left_at(apps, schema_editor):
    Student = apps.get_model('crm', 'Student')
    from django.db.models import F
    Student.objects.filter(status__in=[7, 8], left_at__isnull=True).update(left_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_attendancerecord_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(1, 'Обучается'), (2, 'Заморозка (Frozen)'), (7, 'Ушел после пробного'), (8, 'Отчислен / Ушел'), (9, 'Завершил курс (Graduated)')], default=1),
        ),
        migrations.RunPython(backfill_left_at, migrations.RunPython.noop),
    ]
