# Generated by Django 5.2.15 on 2026-09-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_student_left_at_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('trial_booked', 'Записан на пробный'), ('attended', 'Был на уроке (Думает)'), ('rejected', 'Отказ / Архив')], default='trial_booked', max_length=20),
        ),
    ]
