# Generated by Django 5.2.17 on 2026-09-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_lead_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone2_owner',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='phone2_owner',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
