# Generated by Django 5.2.17 on 2026-09-19 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_lead_phone2_owner_student_phone2_owner'),
        ('org', '0005_company_click_merchant_id_company_click_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='org.branch'),
        ),
        migrations.AddField(
            model_name='lead',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.course'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('trial_booked', 'Записан на пробный'), ('attended', 'Был на уроке (Думает)'), ('rejected', 'Отказ / Архив'), ('converted', 'Зачислен (Студент)')], default='trial_booked', max_length=20),
        ),
    ]
