# Generated by Django 5.2.17 on 2026-09-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_seed_default_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='level',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
