# Generated by Django 5.2.17 on 2026-09-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_lead_level_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='school',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
