# Generated by Django 5.2.17 on 2026-09-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_lead_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('trial_booked', 'Записан на пробный'), ('attended', 'Был на уроке (Думает)'), ('rejected', 'Отказ'), ('converted', 'Зачислен (Студент)')], default='trial_booked', max_length=20),
        ),
    ]
