# Generated by Django 5.2.17 on 2026-09-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_alter_lead_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='attended_trial',
            field=models.BooleanField(default=False),
        ),
    ]
