# Generated by Django 5.2.17 on 2026-09-20 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_group_archived_at_group_archived_by'),
        ('org', '0005_company_click_merchant_id_company_click_secret_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('transferred', 'Transferred'), ('graduated', 'Graduated'), ('left', 'Left')], default='active', max_length=20)),
                ('joined_date', models.DateField()),
                ('left_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['company', 'attend_date'], name='crm_attenda_company_5a791f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['group', 'attend_date'], name='crm_attenda_group_i_bae72b_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('company', 'student', 'group', 'attend_date'), name='uniq_student_attendance_per_group_day'),
        ),
        migrations.AddField(
            model_name='groupenrollment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_enrollments', to='org.company'),
        ),
        migrations.AddField(
            model_name='groupenrollment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='crm.group'),
        ),
        migrations.AddField(
            model_name='groupenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='crm.student'),
        ),
        migrations.AddField(
            model_name='groupscheduleslot',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='crm.group'),
        ),
        migrations.AddField(
            model_name='groupscheduleslot',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='org.room'),
        ),
        migrations.AddIndex(
            model_name='groupenrollment',
            index=models.Index(fields=['company', 'student'], name='crm_groupen_company_c8d231_idx'),
        ),
        migrations.AddIndex(
            model_name='groupenrollment',
            index=models.Index(fields=['group', 'status'], name='crm_groupen_group_i_5d4f96_idx'),
        ),
        migrations.AddIndex(
            model_name='groupscheduleslot',
            index=models.Index(fields=['group', 'weekday'], name='crm_groupsc_group_i_c66457_idx'),
        ),
    ]
