# Generated by Django 5.2.17 on 2026-09-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_backfill_slots_and_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
