# Generated by Django 5.2.17 on 2026-09-24 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_student_frozen_at'),
        ('org', '0006_remove_company_balance_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='group',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='org.branch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='org.branch'),
        ),
    ]
