# Generated by Django 5.2.17 on 2026-09-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_unique_open_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.PositiveIntegerField(default=12, verbose_name='Длительность курса (месяцы)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson_duration',
            field=models.PositiveIntegerField(default=90, verbose_name='Длительность урока (минуты)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Цена в месяц (UZS)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
