# Generated by Django 5.2.17 on 2026-09-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_p4_hygiene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.IntegerField(choices=[(1, 'Был'), (0, 'Не был'), (2, 'Опоздал')], default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='days',
            field=models.IntegerField(choices=[(1, 'Нечётные дни'), (2, 'Чётные дни'), (3, 'Выходные'), (4, 'Каждый день'), (5, 'Свои дни')], default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.IntegerField(choices=[(2, 'Активная'), (3, 'В архиве')], default=2),
        ),
        migrations.AlterField(
            model_name='groupenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Учится'), ('frozen', 'Заморозка'), ('transferred', 'Переведён'), ('graduated', 'Завершил курс'), ('left', 'Ушёл')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(1, 'Обучается'), (2, 'Заморозка'), (7, 'Ушел после пробного'), (8, 'Отчислен / Ушел'), (9, 'Завершил курс')], default=1),
        ),
    ]
