# Generated by Django 5.2.17 on 2026-09-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_russian_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='wallet_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
