# Generated by Django 5.2.17 on 2026-09-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='balance',
        ),
    ]
