# Generated by Django 5.2.17 on 2026-09-28 17:10

import django.db.models.deletion
from django.db import migrations, models


def open_current_freezes(apps, schema_editor):
    # Students frozen right now: an open freeze from the day they were frozen (past freezes are not known)
    from django.utils import timezone

    Student = apps.get_model('crm', 'Student')
    StudentFreeze = apps.get_model('crm', 'StudentFreeze')
    for student in Student.objects.filter(status=2):
        start = timezone.localtime(student.frozen_at).date() if student.frozen_at else timezone.localdate()
        StudentFreeze.objects.create(company_id=student.company_id, student_id=student.id, start_date=start)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_remove_student_balance'),
        ('org', '0007_room_company_branch_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_freezes', to='org.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezes', to='crm.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'start_date'], name='crm_student_student_65176c_idx')],
            },
        ),
        migrations.RunPython(open_current_freezes, migrations.RunPython.noop),
    ]
