# Generated by Django 5.2.17 on 2026-10-05 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def first_prices(apps, schema_editor):
    """Every course that already exists gets its first price record: the price it has now."""
    Course = apps.get_model('crm', 'Course')
    CoursePrice = apps.get_model('crm', 'CoursePrice')
    for course in Course.objects.all():
        if CoursePrice.objects.filter(course=course).exists():
            continue
        day = timezone.localtime(course.created_at).date() if course.created_at else timezone.localdate()
        CoursePrice.objects.create(course=course, price=course.price or 0, valid_from=day)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_student_freeze_journal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('valid_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='crm.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['valid_from', 'id'],
                'constraints': [models.UniqueConstraint(fields=('course', 'valid_from'), name='uniq_course_price_per_day')],
            },
        ),
        migrations.RunPython(first_prices, migrations.RunPython.noop),
    ]
