# Generated by Django 5.2.17 on 2026-10-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_course_price_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='charge_resume_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
