# Generated by Django 5.2.17 on 2026-10-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_month_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payment_offset',
        ),
    ]
