# Generated by Django 5.2.15 on 2026-06-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='UZS', max_length=8),
        ),
        migrations.AddField(
            model_name='company',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(default='Asia/Tashkent', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
