# Generated by Django 5.2.15 on 2026-06-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='grade_pass_score',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='company',
            name='grade_scale_max',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='company',
            name='sms_advance_text',
            field=models.TextField(blank=True, default="Assalomu alaykum! Eslatma: ertaga dars uchun to'lov qilishingiz kerak."),
        ),
        migrations.AddField(
            model_name='company',
            name='voip_caller_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='voip_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='voip_gateway',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
