# Generated by Django 5.2.15 on 2026-09-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_company_settings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='click_merchant_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='click_secret_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='company',
            name='click_service_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='payme_merchant_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='payme_secret_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='company',
            name='uzum_merchant_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
