# Generated by Django 5.2.17 on 2026-09-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_company_click_merchant_id_company_click_secret_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='balance_mode',
        ),
    ]
