# Generated by Django 5.2.15 on 2026-06-10 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_job_title'),
        ('org', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='honorific',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='TeacherBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to='org.branch')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('teacher', 'branch')},
            },
        ),
    ]
