# Generated by Django 5.2.17 on 2026-09-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_staff_role'),
        ('org', '0007_room_company_branch_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherbranch',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='teacherbranch',
            constraint=models.UniqueConstraint(fields=('teacher', 'branch'), name='uniq_teacher_branch'),
        ),
    ]
