# Generated by Django 5.2.17 on 2026-09-25 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_p4_hygiene'),
        ('org', '0007_room_company_branch_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directors', to='org.branch', verbose_name='Филиал директора'),
        ),
    ]
