# Generated by Django 5.2.17 on 2026-09-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('ceo', 'CEO'), ('administrator', 'Администратор'), ('branch_director', 'Директор филиала'), ('limited_admin', 'Ограниченный админ'), ('marketer', 'Маркетолог'), ('cashier', 'Кассир')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('staff', 'Сотрудник'), ('teacher', 'Учитель'), ('student', 'Студент')], default='staff', max_length=20),
        ),
    ]
