# Generated by Django 5.2.17 on 2026-09-28 16:21

from django.db import migrations, models


def merge_old_roles(apps, schema_editor):
    # Owner (2026-09-28): "limited admin" and "cashier" became the one role "administrator"
    User = apps.get_model('accounts', 'User')
    User.objects.filter(staff_role__in=['limited_admin', 'cashier']).update(staff_role='administrator')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_russian_labels'),
    ]

    operations = [
        migrations.RunPython(merge_old_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('ceo', 'CEO'), ('administrator', 'Администратор'), ('branch_director', 'Директор филиала'), ('marketer', 'Маркетолог')], default='', max_length=32),
        ),
    ]
