# Generated by Django 5.2.15 on 2026-06-10 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_teacher_attendance_record'),
        ('org', '0003_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorklyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('at_work', 'At work'), ('late_in', 'Late in'), ('absent', 'Absent')], default='at_work', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workly_records', to='org.company')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workly_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'work_date'], name='operations__company_8aee86_idx')],
                'unique_together': {('company', 'staff', 'work_date')},
            },
        ),
    ]
