# Generated by Django 5.2.15 on 2026-06-10 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_workly_record'),
        ('org', '0004_company_settings_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='archivedperson',
            index=models.Index(fields=['company', 'archived_at'], name='operations__company_b6904e_idx'),
        ),
        migrations.AddField(
            model_name='archivereason',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_reasons', to='org.company'),
        ),
    ]
