# Generated by Django 5.2.15 on 2026-09-04 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_student_parent_telegram_student_telegram'),
        ('operations', '0004_archive_reason'),
        ('org', '0004_company_settings_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=64)),
                ('trigger_date', models.DateField()),
                ('target', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField()),
                ('ok', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='org.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='crm.student')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'rule', 'trigger_date'], name='operations__company_d6f294_idx'), models.Index(fields=['student', 'created_at'], name='operations__student_47e70a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ok', True)), fields=('student', 'rule', 'trigger_date'), name='uniq_ok_notification_per_day')],
            },
        ),
    ]
