# Generated by Django 5.2.17 on 2026-09-20 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_notificationlog'),
        ('org', '0005_company_click_merchant_id_company_click_secret_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=32)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_records', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log_records', to='org.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'entity_type', 'created_at'], name='operations__company_bcd6a6_idx'), models.Index(fields=['entity_type', 'entity_id'], name='operations__entity__c516db_idx')],
            },
        ),
    ]
