# Generated by Django 5.2.17 on 2026-09-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auditlogrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
