# Generated by Django 5.2.17 on 2026-09-25 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_p4_hygiene'),
        ('operations', '0008_unique_tag_score_holiday'),
        ('org', '0007_room_company_branch_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherattendancerecord',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='worklyrecord',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='teacherattendancerecord',
            constraint=models.UniqueConstraint(fields=('company', 'teacher', 'group', 'attend_date'), name='uniq_teacher_attendance_per_day'),
        ),
        migrations.AddConstraint(
            model_name='worklyrecord',
            constraint=models.UniqueConstraint(fields=('company', 'staff', 'work_date'), name='uniq_workly_per_day'),
        ),
    ]
