# Generated by Django 5.2.17 on 2026-09-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_p4_hygiene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('overdue', 'Просрочено'), ('today', 'Сегодня'), ('future', 'Предстоит'), ('done', 'Выполнено')], default='today', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherattendancerecord',
            name='status',
            field=models.IntegerField(choices=[(1, 'Был'), (0, 'Не был'), (2, 'Опоздал')], default=1),
        ),
        migrations.AlterField(
            model_name='worklyrecord',
            name='status',
            field=models.CharField(choices=[('at_work', 'На работе'), ('late_in', 'Опоздал'), ('absent', 'Отсутствовал')], default='at_work', max_length=16),
        ),
    ]
