# Generated by Django 5.2.17 on 2026-09-27 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_russian_labels'),
        ('operations', '0010_russian_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='reminder',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='crm.student'),
        ),
    ]
