# Generated by Django 5.2.17 on 2026-09-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_reminder_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='resolution',
            field=models.TextField(blank=True, default=''),
        ),
    ]
