# Generated by Django 5.2.17 on 2026-09-28 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_old_write_offs(apps, schema_editor):
    # Debts the CEO wrote off before this field existed (the resolution text says so)
    Reminder = apps.get_model('operations', 'Reminder')
    Reminder.objects.filter(kind='unpaid_leave', resolution__startswith='Долг списан').update(written_off=True)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_reminder_resolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='written_off',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_old_write_offs, migrations.RunPython.noop),
    ]
