# Generated by Django 5.2.17 on 2026-09-28 14:02

from decimal import ROUND_HALF_UP, Decimal

from django.db import migrations, models


def round_old_grades(apps, schema_editor):
    # Owner (2026-09-28): whole points only. 99.5 -> 100, 99.4 -> 99 before the column becomes an integer.
    StudentScore = apps.get_model('operations', 'StudentScore')
    for score in StudentScore.objects.all():
        whole = Decimal(score.grade).quantize(Decimal('1'), rounding=ROUND_HALF_UP)
        if whole != score.grade:
            StudentScore.objects.filter(pk=score.pk).update(grade=whole)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_reminder_owner_writeoff'),
    ]

    operations = [
        migrations.RunPython(round_old_grades, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentscore',
            name='grade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
