# Generated by Django 5.2.17 on 2026-09-28 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def history_for_existing_grades(apps, schema_editor):
    # Grades given before the history existed: one record each, dated by the last change (Tashkent day)
    from django.utils import timezone

    StudentScore = apps.get_model('operations', 'StudentScore')
    StudentScoreHistory = apps.get_model('operations', 'StudentScoreHistory')
    for score in StudentScore.objects.select_related('group', 'group__course'):
        StudentScoreHistory.objects.create(
            company_id=score.company_id,
            student_id=score.student_id,
            score=score,
            group_id=score.group_id,
            group_name=score.group.name if score.group_id else '',
            course_name=score.group.course.name if score.group_id and score.group.course_id else '',
            grade=score.grade,
            graded_on=timezone.localtime(score.updated_at).date(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_remove_student_balance'),
        ('operations', '0014_score_whole_points'),
        ('org', '0007_room_company_branch_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=255)),
                ('course_name', models.CharField(blank=True, max_length=255)),
                ('grade', models.PositiveIntegerField()),
                ('graded_on', models.DateField()),
                ('corrected', models.BooleanField(default=False)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='org.company')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.group')),
                ('score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='operations.studentscore')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='crm.student')),
            ],
            options={
                'ordering': ['-graded_on', '-id'],
            },
        ),
        migrations.RunPython(history_for_existing_grades, migrations.RunPython.noop),
    ]
