# Generated by Django 5.2.17 on 2026-09-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_score_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorklyRecord',
        ),
    ]
