# Generated by Django 5.2.17 on 2026-10-05 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_month_lines'),
        ('operations', '0016_remove_workly'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='crm.group'),
        ),
    ]
