# Generated by Django 5.2.17 on 2026-10-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_month_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendancerecord',
            name='percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
