# Generated by Django 5.2.15 on 2026-09-14 15:48

import django.db.models.deletion
from django.db import migrations, models


def backfill_students(apps, schema_editor):
    Payment = apps.get_model('finance', 'Payment')
    Student = apps.get_model('crm', 'Student')
    for payment in Payment.objects.filter(student__isnull=True):
        if not payment.student_name:
            continue
        p_name = payment.student_name.strip().lower()
        matched = None
        for s in Student.objects.filter(company_id=payment.company_id):
            full = f"{s.first_name} {s.last_name}".strip().lower()
            rev = f"{s.last_name} {s.first_name}".strip().lower()
            if full == p_name or rev == p_name or s.first_name.strip().lower() == p_name:
                matched = s
                break
        if matched:
            payment.student = matched
            payment.save(update_fields=['student'])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_attendancerecord_note'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='months_covered',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crm.student'),
        ),
        migrations.RunPython(backfill_students, migrations.RunPython.noop),
    ]

