# Generated by Django 5.2.17 on 2026-09-23 08:13

import django.db.models.deletion
from django.db import migrations, models


def populate_payment_date(apps, schema_editor):
    Payment = apps.get_model('finance', 'Payment')
    for payment in Payment.objects.filter(payment_date__isnull=True):
        if payment.created_at:
            payment.payment_date = payment.created_at.date()
            payment.save(update_fields=['payment_date'])


def deduplicate_payment_transactions(apps, schema_editor):
    PaymentTransaction = apps.get_model('finance', 'PaymentTransaction')
    seen = set()
    for t in PaymentTransaction.objects.all().order_by('id'):
        key = (t.company_id, t.provider, t.trans_id)
        if key in seen:
            t.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_student_frozen_at'),
        ('finance', '0006_link_salary_and_payment_snapshots'),
        ('org', '0006_remove_company_balance_mode'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='finance_pay_company_bcfdc4_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(populate_payment_date, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='crm.student'),
        ),
        migrations.RunPython(deduplicate_payment_transactions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(fields=('company', 'provider', 'trans_id'), name='uniq_provider_transaction'),
        ),
    ]
