# Generated by Django 5.2.17 on 2026-09-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_unique_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gross_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='net_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payrollpayment',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='salarysetting',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
