# Generated by Django 5.2.17 on 2026-09-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_p4_hygiene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Оплата'), ('refund', 'Возврат'), ('adjustment', 'Корректировка')], default='payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Проведён'), ('cancelled', 'Отменён')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='salarysetting',
            name='salary_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная'), ('percent', 'Процент'), ('per_student', 'За студента')], default='fixed', max_length=20),
        ),
    ]
