# Generated by Django 5.2.17 on 2026-09-27 12:42

from django.db import migrations, models
from django.db.models import Sum


def fill_refunded_months(apps, schema_editor):
    """Existing refunds: take back whole months only (a full refund takes back all of them)."""
    Payment = apps.get_model('finance', 'Payment')
    refunded = (
        Payment.objects.filter(transaction_type='refund', reverses_payment__isnull=False)
        .values('reverses_payment_id').annotate(total=Sum('amount'))
    )
    for row in refunded:
        payment = Payment.objects.filter(pk=row['reverses_payment_id']).first()
        if payment is None or not payment.months_covered or not payment.amount:
            continue
        total = row['total'] or 0
        if total >= payment.amount:
            months = payment.months_covered
        else:
            months = min(payment.months_covered, total * payment.months_covered // payment.amount)
        if months:
            Payment.objects.filter(pk=payment.pk).update(refunded_months=months)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_russian_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refunded_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(fill_refunded_months, migrations.RunPython.noop),
    ]
