# Generated by Django 5.2.17 on 2026-09-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_payment_refunded_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
