# Generated by Django 5.2.17 on 2026-09-28 16:39

import django.db.models.deletion
from django.db import migrations, models


def fill_dates_and_branches(apps, schema_editor):
    # Old records: the date is the day they were typed in (Tashkent); old expenses get the first branch
    # of the company (the data is test data, the owner can change it in the form)
    from django.utils import timezone

    Expense = apps.get_model('finance', 'Expense')
    Withdrawal = apps.get_model('finance', 'Withdrawal')
    Branch = apps.get_model('org', 'Branch')
    first_branch = {}
    for expense in Expense.objects.all():
        if expense.company_id not in first_branch:
            first_branch[expense.company_id] = (
                Branch.objects.filter(company_id=expense.company_id).order_by('id').values_list('id', flat=True).first()
            )
        Expense.objects.filter(pk=expense.pk).update(
            expense_date=timezone.localtime(expense.created_at).date(),
            branch_id=expense.branch_id or first_branch[expense.company_id],
        )
    for withdrawal in Withdrawal.objects.all():
        Withdrawal.objects.filter(pk=withdrawal.pk).update(
            withdrawal_date=timezone.localtime(withdrawal.created_at).date(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_wallet'),
        ('org', '0007_room_company_branch_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='org.branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawal_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(fill_dates_and_branches, migrations.RunPython.noop),
    ]
