# Generated by Django 5.2.17 on 2026-09-28 17:10

import django.db.models.deletion
from django.db import migrations, models


def teachers_percent_only(apps, schema_editor):
    # Owner (2026-09-28): teachers have only a percent — fixed / per-student rates of teachers are removed
    # (they were test data); a fixed monthly amount stays only for office staff
    SalarySetting = apps.get_model('finance', 'SalarySetting')
    SalarySetting.objects.filter(salary_type='per_student').delete()
    SalarySetting.objects.filter(teacher__user_type='teacher').exclude(salary_type='percent').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_expense_branch_and_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payroll_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_expenses', to='finance.payrollpayment'),
        ),
        migrations.AlterField(
            model_name='salarysetting',
            name='salary_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная'), ('percent', 'Процент')], default='fixed', max_length=20),
        ),
        migrations.RunPython(teachers_percent_only, migrations.RunPython.noop),
    ]
