# Generated by Django 5.2.17 on 2026-09-29 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_payroll_by_branch'),
        ('org', '0007_room_company_branch_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_months', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_months', to='org.company')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_period', models.CharField(max_length=7)),
                ('amount', models.BigIntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='org.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_adjustments', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrued', models.BigIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('closed_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='finance.closedmonth')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='closedmonth',
            constraint=models.UniqueConstraint(fields=('company', 'month'), name='uniq_closed_month'),
        ),
        migrations.AddConstraint(
            model_name='payrollsnapshot',
            constraint=models.UniqueConstraint(fields=('closed_month', 'person'), name='uniq_payroll_snapshot'),
        ),
    ]
