# Generated by Django 5.2.17 on 2026-10-05 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_month_lines'),
        ('finance', '0015_month_closing'),
        ('org', '0007_room_company_branch_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('pay_day', models.PositiveSmallIntegerField()),
                ('price', models.BigIntegerField()),
                ('discount', models.BigIntegerField(default=0)),
                ('amount', models.BigIntegerField()),
                ('paid_amount', models.BigIntegerField(default=0)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('lessons_planned', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Действует'), ('written_off', 'Списано CEO')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_charges', to='org.company')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='crm.course')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='crm.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='crm.student')),
            ],
            options={
                'ordering': ['student_id', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.payment')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.studentcharge')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentcharge',
            constraint=models.UniqueConstraint(fields=('student', 'seq'), name='uniq_student_charge_seq'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'charge'), name='uniq_payment_charge_allocation'),
        ),
    ]
