# Generated by Django 5.2.17 on 2026-10-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_month_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount_months',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
