# Generated by Django 5.2.17 on 2026-10-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_payment_discount_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='refunded_months',
        ),
    ]
